# Generated by Django 6.0.5 on 2026-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_temporary_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temporary_password_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
